name: Build Emojis

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run Script
        run: bash build_font.sh

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          path: nanoemoji/build/
