name: Build Emojis

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install python 3
        uses: actions/setup-python@v4

      - run: bash build_font.sh

      - name: Upload Font Artifact
        uses: actions/upload-artifact@v3
        with:
          path: nanoemoji/build/